parameters:
#    myweb_index.example.class: Myweb\IndexBundle\Example

services:
#    myweb_index.example:
#        class: %myweb_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
